MA-10: Create "Products" page
FlutterMeta/MetaApp pull request #12
Opened 2022-10-24 07:15 UTC by vitalii-petrun

2022-10-26 10:10 UTC, vovaklh requested changes

2022-10-26 10:10 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/gradient_section.dart
> +List<_InfoBlock> _statsInfoBlocks(BuildContext context) {
Make List<Widget>

2022-10-26 10:10 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/partners_section.dart
> +}
Pls delete this for now

2022-10-26 10:10 UTC, vovaklh commented on lib/presentation/themes/src/theme_text_styles.dart
> +  final TextStyle productsHeadlineMedium;
Rename pls, delete "medium"

2022-10-26 10:36 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/sections/gradient_section.dart
> +      width: context.screenWidth,
it's not needed, sorry

2022-10-26 10:42 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +class _FaqItem extends StatefulWidget {
my bad

2022-10-26 11:17 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/products_page.dart
> +          const SliverSizedBox(child: Align(child: _PresentationSection())),
to make constraints work

2022-10-26 17:16 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/sections/investors_section.dart
> +      child: LayoutBuilder(
actually we can use Wrap, but on original web site this section has behaviour more like I described via LayoutBuilder

I think I shouls use just Wrap

2022-10-26 17:20 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/sections/investors_section.dart
> +                : context.screenWidth * 0.22,
I applied it for all InvestorComponent, as it was meant

it gives constrained and responsive blocks called InvestorComponent which are columns with text

2022-10-26 18:05 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +      child: Column(
we already have customscrollview, it's not recommended to use another scrollable (ListView.separated) inside of it

2022-10-27 16:33 UTC, vovaklh requested changes

2022-10-27 16:33 UTC, vovaklh commented on lib/l10n/app_ru.arb
> -    "ukrainian": "Українська",
Why deleted this string?

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/products_page.dart
> +          const SliverToBoxAdapter(child: Footer()),
Pls delete all Align widgets and use alignment in sections

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/products_page.dart
> +      constraints: const BoxConstraints(maxWidth: 1270),
I think you should replace Container width ConstrainedBox and replace padding by SliverSizedBox where divider is used

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/components_section.dart
> +      child: ConstrainedBox(
I think ConstrainedBox should be above padding

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/components_section.dart
> +            Align(
Why using Align withoud alignment property?

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/components_section.dart
> +  const _ComponentsSection();
Add key pls

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +      ),
It shouldn't be in items. Move it and replace method by variable

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +        },
Replace by =>

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +        itemBuilder: (BuildContext context, int index) {
Replace BuildContext by _, and delete type from index

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +        separatorBuilder: (BuildContext context, int index) {
Replace by _, __

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +      Tween<double>(begin: 0.0, end: 0.25);
Static variables should be above var variables

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +  }
It should below build method

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +  }
Look bad

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/faq_section.dart
> +                    Text(widget.answer, style: context.text.productsFaqAnswer),
Add comma

2022-10-27 16:33 UTC, vovaklh commented on lib/presentation/pages/products_page/sections/gradient_section.dart
> +  final String? description;
Set default value as empty string in constructor

2022-10-28 07:07 UTC, vitalii-petrun commented on lib/l10n/app_ru.arb
> -    "ukrainian": "Українська",
this string changed its locatiion after merge dev into this branch

2022-10-28 07:07 UTC, vitalii-petrun commented on lib/presentation/pages/products_page/sections/components_section.dart
> +            Align(
it has Alignment.center as default value

2022-10-29 15:29 UTC, vovaklh approved these changes

2022-10-29 15:30 UTC, merged