MA-28: Create Client profile Bots page
FlutterMeta/MetaApp pull request #31
Opened 2023-01-20 20:33 UTC by vitalii-petrun

2023-01-22 10:16 UTC, vovaklh requested changes

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +            const TextSpan(text: "  "),
Ca we delete this and wrap previous text span in "$...   "?

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +          },
Pls move to separate method

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  );
Same as above

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  );
Same as above

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +            Text(context.localizations.chooseNetwork, style: _labelTextStyle),
Add comma

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  static const _hintTextStyle = TextStyle(fontSize: 16);
Delete

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  static final _transactions = [
Make const and not static

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  );
Move

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +        color: AppColors.white,
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  static const _transactionTextStyle = TextStyle(
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +                color: AppColors.black,
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +                  ),
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +                ),
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +    );
Inside build...

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/dashboard_tab.dart
> +  canceled("Cancelled");
I think it should be localized

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/side_menu_section.dart
> +    super.initState();
IninState in first place

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/side_menu_section.dart
> +                      : AppColors.transparent,
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/side_menu_section.dart
> +                            : context.color.dashboardSideMenuUnselectedItem),
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/widgets/dashboard_header.dart
> +                hoverColor: AppColors.transparent,
Styles

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/widgets/dashboard_header.dart
> +      _animationController.reverse().then((value) => _overlayEntry?.remove());
Dont use then, use await

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/widgets/dashboard_header.dart
> +    const userNameStyle = TextStyle(fontSize: 16, fontWeight: FontWeight.bold);
Move

2023-01-22 10:16 UTC, vovaklh commented on lib/presentation/widgets/dashboard_header.dart
> +            color: AppColors.white,
Move

2023-01-25 19:13 UTC, vovaklh requested changes

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +}
Pls delete

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +                        style: context.text.inverseBody.copyWith(fontSize: 11),
12

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +      fontSize: Responsive.isMobile(context) ? 14 : 17,
18

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +  static final _fourChecks = List.generate(
remove pls static

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +      fontSize: Responsive.isMobile(context) ? 12 : 15,
16

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/constants.dart
> +  static const greyish = Color(0xFF7E7E7E);
Pls rename

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/constants.dart
> +  static const greyishIndigo = Color(0xFF464A53);
Pls rename

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/theme_colors.dart
> +  final Color onBackground;
The on is associated with callback. Pls rename

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/theme_colors.dart
> +  final Color primary;
Make primary for this page

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/theme_colors.dart
> +  final Color primaryVariant;
Rename pls

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/theme_colors.dart
> +  final Color secondaryVariant;
Associate with page or widget

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/themes/src/theme_text_styles.dart
> +  final TextStyle inverseBody;
Associate with page or widget

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/widgets/dashboard_header.dart
> +                splashColor: context.color.transparent,
Pls rename transparent color in styles. Associate with page...

2023-01-25 19:13 UTC, vovaklh commented on lib/presentation/widgets/dashboard_header.dart
> +        context.text.body.copyWith(fontSize: 16, fontWeight: FontWeight.bold);
Pls delete variable and use directly

2023-01-26 11:23 UTC, vitalii-petrun commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +  static final _fourChecks = List.generate(
![image](https://user-images.githubusercontent.com/87064627/214823854-97f6464a-9949-4260-aec0-76e77b4ab16b.png)

2023-01-26 18:48 UTC, vovaklh approved these changes

2023-01-26 18:49 UTC, merged