MA-29: Create Client profile Deposit confirmation page
FlutterMeta/MetaApp pull request #32
Opened 2023-01-24 21:46 UTC by vitalii-petrun

2023-01-29 09:25 UTC, vovaklh requested changes

2023-01-29 09:25 UTC, vovaklh commented on lib/core/mixins/validator.dart
> +    } else if ((password ?? '')
There is no need for this because there is isNullOrEmpty above

2023-01-29 09:25 UTC, vovaklh commented on lib/main.dart
> +      create: (_) => MenuCubit(),
Pls use DI with injectable
Check for example
https://github.com/vovaklh/HdRezkaApp/blob/dev/lib/core/di/modules/cubit_module.dart

2023-01-29 09:25 UTC, vovaklh commented on lib/main_storybook.dart
> +    create: (context) => MenuCubit(),
Same as above and add comma

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/blocs/client_profile_page/menu_cubit.dart
> +          scaffoldKey: GlobalKey<ScaffoldState>(),
The Bloc is bussiness logic component. There shoud not be any UI components. Delete scaffoldKey

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/blocs/client_profile_page/menu_cubit.dart
> +  void changeCollapsedState() {
Pls pass parameter collapsed and use it

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/blocs/client_profile_page/menu_state.dart
> +}
Use freezed for states

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/blocs/client_profile_page/menu_cubit.dart
> +    ));
Replace by copyWith

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/client_profile_page.dart
> +      key: context.read<MenuCubit>().state.scaffoldKey,
Looks bad

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/client_profile_page.dart
>          return const DashboardTab();
You should have a list of tabs

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/client_profile_page.dart
> +          child: chooseTab(menu.tabIndex),
tabs[index]

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/transaction.dart
> +  canceled("Cancelled");
I think it should be localized

2023-01-29 09:25 UTC, vovaklh commented on lib/presentation/widgets/profile_header.dart
> +
Pls delete

2023-02-02 13:46 UTC, vitalii-petrun commented on lib/main.dart
> +      create: (_) => MenuCubit(),
I'll sort it out with https://habr.com/ru/post/654119/ and  https://www.youtube.com/playlist?list=PLrnbjo4fMQwZlSsDGpAQXustsSIpqDwir

2023-02-02 13:47 UTC, vitalii-petrun commented on lib/presentation/blocs/client_profile_page/menu_state.dart
> +}
not relevant now

but gonna check https://pub.dev/packages/freezed

2023-02-02 19:10 UTC, vovaklh requested changes

2023-02-02 19:10 UTC, vovaklh commented on lib/presentation/pages/client_profile_page/sections/side_menu_section.dart
>      setState(() => _currentIndex = index);
Do we need setState here?

2023-02-02 19:11 UTC, vitalii-petrun commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +    const int transactionTabIndex = 2;
then it will be magic number

2023-02-02 19:13 UTC, vitalii-petrun commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +        "\$$price",
it's not text, it's number (price)

2023-02-02 19:22 UTC, vitalii-petrun commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +    const int transactionTabIndex = 2;
you will be right if you say that there is already a lot of these, but this one is important so I decided to make code more readeble and clear

2023-02-02 19:26 UTC, vitalii-petrun commented on lib/presentation/pages/client_profile_page/sections/bots_tab.dart
> +                    }
![image](https://user-images.githubusercontent.com/87064627/216430151-ea8c05b4-0f7f-45e8-83b1-3d0041a94973.png)


:(

2023-02-03 11:41 UTC, vovaklh approved these changes

2023-02-03 11:42 UTC, merged