MA-30: Create Admin profile Dashboard page
FlutterMeta/MetaApp pull request #33
Opened 2023-02-03 11:50 UTC by vitalii-petrun

2023-02-05 09:23 UTC, vitalii-petrun commented on lib/presentation/navigation/app_router.dart
>    ],
all the pages on the same level, so even if it has nested structure, there is no base admin-profile (page)

navigation is handled by clicking on right part of header

![image](https://user-images.githubusercontent.com/87064627/216811182-2d58ce86-4bce-4d03-9a12-11ffe31259b1.png)

2023-02-05 09:24 UTC, vitalii-petrun commented on lib/presentation/pages/admin_profile/dashboard_page.dart
> +class DashboardPage extends StatelessWidget {
future page prototype

2023-02-05 09:28 UTC, vitalii-petrun commented on lib/presentation/pages/admin_profile/financial_indicators_page.dart
> +  List<Widget> _demoCards(BuildContext context) {
... will be updated (admin have ability to change price)

2023-02-05 09:31 UTC, vitalii-petrun commented on lib/presentation/widgets/bot_demo_card.dart
> +class BotDemoCard extends StatelessWidget {
maybe will be renamed

i'm going to create composite structure as with Header, to create named constructors BotDemoCard.client, BotDemoCard.admin

2023-02-05 16:45 UTC, vovaklh requested changes

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/pages/admin_profile/financial_indicators_page.dart
> +    final localization = context.localizations;
Pls delete

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/header.dart
> +  final GlobalKey<ScaffoldState>? scaffoldKey;
Pls pass callback instead of scaffoldKey

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/header.dart
>              ),
looks confusing

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/header.dart
> +class ProfileHeader extends Header {
Maybe move to separate folder

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/header.dart
> +class _SearchBar extends StatelessWidget {
Same as above

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +  final List<Widget> Function(BuildContext context, VoidCallback) items;
Remove "context" from method signature

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +      widget.closeMenuCallback!();
Make widget.closeMenuCallback?.call()

2023-02-05 16:45 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +    Timer(const Duration(milliseconds: 300), () => widget.onTap());
Why we need it?

2023-02-05 20:32 UTC, vitalii-petrun commented on lib/presentation/widgets/profile_header/header.dart
>              ),
it's better than billion of toggles like this:

https://pastebin.com/0Bivf4Ua

2023-02-05 20:33 UTC, vitalii-petrun commented on lib/presentation/widgets/profile_header/menu.dart
> +    Timer(const Duration(milliseconds: 300), () => widget.onTap());
page changes (so context to) but animation of overlay closing by the moment has not ended, so overlay is displaying on new pushed screen

2023-02-05 20:34 UTC, vitalii-petrun commented on lib/presentation/widgets/profile_header/menu.dart
> +    Timer(const Duration(milliseconds: 300), () => widget.onTap());
we need to wait overlay close -> push new page.

2023-02-05 20:35 UTC, vitalii-petrun commented on lib/presentation/pages/admin_profile/financial_indicators_page.dart
> +    final localization = context.localizations;
why?

2023-02-05 20:55 UTC, vitalii-petrun commented on lib/presentation/widgets/profile_header/menu.dart
> +  final List<Widget> Function(BuildContext context, VoidCallback) items;
but I need context to create MenuItems list ...

2023-02-07 18:07 UTC, vovaklh approved these changes

2023-02-07 18:08 UTC, merged