MA-30: Create Admin profile Financial indicators page [PART II]
FlutterMeta/MetaApp pull request #34
Opened 2023-02-08 08:41 UTC by vitalii-petrun

2023-02-08 08:46 UTC, vitalii-petrun commented on lib/presentation/widgets/demo_card.dart
> +    _priceController.text;
it's what admin typed into a text field on the moment of pressing "confirm"

In the future it will be send to backend

2023-02-08 08:54 UTC, vitalii-petrun commented on pubspec.yaml
> +  flutter_portal: ^1.1.3
Flutter Portal is a package which makes Overlay declarative, not imperative. It means Overlay mounted in widget tree as default widget. Otherwise I need to call overlayEnry.insert() and so on. There are some new concepts as a portal, target -they're described in docs. Truly great thing I'd say. 

More: https://pub.dev/packages/flutter_portal

2023-02-08 08:58 UTC, vitalii-petrun commented on lib/presentation/pages/admin_profile/financial_indicators_page.dart
> +      body: Portal(
already described in pubspec.yaml

2023-02-08 09:00 UTC, vitalii-petrun commented on lib/presentation/widgets/admin_window.dart
> +class AdminWindow extends StatelessWidget {
it describes that window:

![image](https://user-images.githubusercontent.com/87064627/217482986-04719e33-aff1-4067-9842-f7f10992f551.png)

2023-02-08 09:05 UTC, vitalii-petrun commented on lib/presentation/widgets/admin_window.dart
> +  final Widget content;
There are a lot of these windows, they all have same design, title and 2 buttons. Main content is different 

![image](https://user-images.githubusercontent.com/87064627/217483329-2da5af7b-14ce-4730-93c7-76305df20f77.png)

![image](https://user-images.githubusercontent.com/87064627/217483367-40ba13b4-da4c-4d05-9514-78339e24482c.png)

so I choose to pass Widget content. 

don't know, maybe it's bad solution

2023-02-08 09:08 UTC, vitalii-petrun commented on lib/presentation/pages/admin_profile/financial_indicators_page.dart
> +      body: Portal(
flutter_portal: Evolved Overlay/OverlayEntry - declarative not imperative, intuitive-context, and easy-alignment

2023-02-12 14:47 UTC, vovaklh requested changes

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/bot_demo_card.dart
> +class BotDemoCard extends DemoCard {
Pls don't extend widgets

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/demo_card.dart
> +  bool _isEditing = false;
Move above

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/demo_card.dart
> +  final _priceController = TextEditingController();
Dispose controller in dispose method

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/editing_field.dart
> +  final dynamic value;
Dont use dynamic

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/level_card.dart
> +class LevelCard extends SimpleCard {
Dont extends widget

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/simple_card.dart
> +  bool _isTapped = false;
Move above

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/simple_card.dart
> +  final _priceController = TextEditingController();
Dispose

2023-02-12 14:47 UTC, vovaklh commented on lib/presentation/widgets/simple_card.dart
> +            return _CardItself(level: widget.level, reward: widget.reward);
Bad name

2023-02-13 17:34 UTC, vovaklh approved these changes

2023-02-13 17:35 UTC, merged