MA-31: Create Admin profile Dashboard page
FlutterMeta/MetaApp pull request #35
Opened 2023-02-09 17:29 UTC by vitalii-petrun

![image](https://user-images.githubusercontent.com/87064627/217891558-e3a0e740-2f53-4970-8f7e-b4a5e84fd6a2.png)

--->

![image](https://user-images.githubusercontent.com/87064627/217891268-1687660a-b9d8-40a4-9b4c-e7709901794d.png)
![image](https://user-images.githubusercontent.com/87064627/217891425-cc147e12-1426-4693-a874-e0137ffd8824.png)
![image](https://user-images.githubusercontent.com/87064627/217891336-5e45d9b6-6c88-4204-81c2-9aa134e0bf04.png)
![image](https://user-images.githubusercontent.com/87064627/217891374-1a2d75ad-22f3-4dba-91d3-6eed58269cc3.png)

2023-02-13 18:43 UTC, vitalii-petrun commented on lib/presentation/widgets/user_table.dart
> +          content: Text(user.name, style: context.text.adminUserTableLabel),
you need only user name (string), AvatarCell widget doesn't require entire instance of User class

2023-02-13 18:43 UTC, vitalii-petrun commented on lib/presentation/widgets/user_table.dart
> +          SizedBox(width: context.screenWidth * 0.01),
remove width: context.screenWidth * 0.01, SizedBox will be  taken into account by  Wrap  widget

2023-02-13 18:43 UTC, vitalii-petrun commented on lib/presentation/widgets/user_table.dart
> +            style: context.text.headerNavItemHovered.copyWith(fontSize: 15),
16

2023-02-14 18:57 UTC, vovaklh requested changes

2023-02-14 18:57 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +    _passwordController.text;
What is it?

2023-02-14 18:57 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +  final _passwordController = TextEditingController();
Dispose controllers

2023-02-14 18:57 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +  final _wallet4Controller = TextEditingController(text: _mockWallets.last);
Dispose

2023-02-14 18:57 UTC, vovaklh commented on lib/presentation/widgets/profile_header/menu.dart
> +class _EditRequisitesMenuItem extends StatefulWidget {
Pls move long widgets to separate folder

2023-02-14 18:57 UTC, vovaklh commented on lib/presentation/widgets/user_table.dart
> +class User {
Pls create for now folder models in data folder and move all models and connected enums there. For example, Transaction model also

2023-02-14 19:04 UTC, vitalii-petrun commented on lib/presentation/widgets/profile_header/menu.dart
> +    _passwordController.text;
data which will be sent to back-end

2023-02-14 19:32 UTC, vitalii-petrun commented on lib/presentation/widgets/profile_header/menu.dart
> +class _EditRequisitesMenuItem extends StatefulWidget {
refactored on MA-32 by mistake, but actually it's even better, because that branch also has refactored UserTable.

2023-02-15 17:11 UTC, vovaklh approved these changes

2023-02-15 17:12 UTC, merged