MA-33: Create Admin profile AllUsers/User transaction page
FlutterMeta/MetaApp pull request #37
Opened 2023-02-18 10:54 UTC by vitalii-petrun

https://user-images.githubusercontent.com/87064627/219856522-89e2ae67-eaa3-44e3-bade-091521907f0e.mp4

2023-02-20 11:41 UTC, vitalii-petrun commented on lib/presentation/pages/admin_profile/user_transactions_page.dart
> +  final bool? showPendingTransactions;
DashboardPage has option to show user's pending transactions. It pushes UserTransactionsPage with already filtered list

2023-02-26 14:21 UTC, vovaklh requested changes

2023-02-26 14:21 UTC, vovaklh commented on lib/data/models/user.dart
> +        referrals = [];
I think it isn't part of User model

2023-02-26 14:21 UTC, vovaklh commented on lib/l10n/app_en.arb
> +    "paySystem": "Pay. system",
Do we need dot here?

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/dashboard_page.dart
> +      transactionsHistory: transactions,
I think it should be refactored

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/transactions_page.dart
> +      body: Portal(
Wy using empty Portal widget?

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/transactions_page.dart
> +final mockTransactions = [
Make part of class

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/user_transactions_page.dart
> +  final bool? showPendingTransactions;
Set default to false

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/user_transactions_page.dart
> +      body: Portal(
Why usign empty Portal?

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/user_transactions_page.dart
> +  late List<Transaction> transactionsHistory;
Add empty space

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/user_transactions_page.dart
> +      return transaction.status.toLowerCase() == 'pending';
Change string to enum

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/pages/admin_profile/user_transactions_page.dart
> +    super.initState();
Shoul be called at the first place

2023-02-26 14:21 UTC, vovaklh commented on lib/presentation/widgets/transaction_table/components/transaction_info.dart
> +  }
I dont like this. Make private for now

2023-02-26 14:24 UTC, vitalii-petrun commented on lib/l10n/app_en.arb
> +    "paySystem": "Pay. system",
shortened version of Payment.

2023-02-26 14:42 UTC, vitalii-petrun commented on lib/l10n/app_en.arb
> +    "paySystem": "Pay. system",
![image](https://user-images.githubusercontent.com/87064627/221417439-70a591a9-19d8-4f2f-836f-51450bcde844.png)

2023-03-02 15:46 UTC, vovaklh approved these changes

2023-03-02 15:47 UTC, merged